### ISSUE TITLE
expected ID and related error

### ISSUE THREAD

**Issue by JasonK80** [allenai/pdffigures2#22]
The following error message occurs during build_evaluation.py execution:
I have no idea about this error. How could I solve it?

(base) C:\Users\user\Study\scala\pdffigures2-master\pdffigures2-master\evaluation>python build_evaluation.py conference pdffigures2 -o new_evaluation.pkl
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Evaluating pdffigures2 (0.0.12-SNAPSHOT)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[Traceback (most recent call last):
  File "build_evaluation.py", line 223, in <module>
    main()
  File "build_evaluation.py", line 196, in main
    evaluated_figures = evaluate(dataset, extractor, doc_ids_to_use, compare_caption_text, crop, verbose)
  File "build_evaluation.py", line 125, in evaluate
    extractor.start_batch([x.pdffile for x in documents])
  File "C:\Users\user\Study\scala\pdffigures2-master\pdffigures2-master\evaluation\extractors.py", line 75, in start_batch
info] Loading project definition from C:\Users\user\Study\scala\pdffigures2-master\pdffigures2-master\project
    (exit_code, " ".join(args)))
ValueError: Non-zero exit status 3221226505, call:
sbt -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider run C:\Users\user\Study\scala\pdffigures2-master\pdffigures2-master\evaluation\datasets\conference\pdfs\aaai10_2.pdf,C:\Users\user\Study\scala\pdffigures2-master\pdffigures2-master\evaluation\datasets\conference\pdfs\aaai10_3.pdf,C:\Users\user\Study\scala\pdffigures2-master\pdffigures2-master\evaluation\datasets\conference\pdfs\aaai10_1.pdf -c -d C:\Users\user\AppData\Local\Temp\tmpbkrvdsox/ -e -q

(base) C:\Users\user\Study\scala\pdffigures2-master\pdffigures2-master\evaluation>Missing bintray credentials C:\Users\user\.bintray\.credentials. Some bintray features depend on this.
[info] Set current project to pdffigures2 (in build file:/C:/Users/user/Study/scala/pdffigures2-master/pdffigures2-master/)
[error] Expected ID character
[error] Not a valid command: sun (similar: plugin, set)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: sun (similar: run, runner, sbtPlugin)
[error] sun.java2d.cmm.kcms.KcmsServiceProvider
[error]    ^

**Comment by Binhao-Wang** [comment]
I encountered this error, too. I don't know how to fix it. Is there anyone who can help?

**Comment by JaniceXiong** [comment]
I encountered this error too

**Comment by SWHL** [comment]
I meet the same problem.

**Comment by SWHL** [comment]
Prerequisite is that Java is installed.

I know the right way as following:
```bash
$ cd pdffigures2
$ sbt assembly
```
