### ISSUE TITLE
Page 2 is an image and allow OCR is false, giving up

### ISSUE THREAD

**Issue by vikram-ce** [allenai/pdffigures2#23]
10:40:30.718 [main] DEBUG o.a.pdffigures2.GraphicsExtractor$ - Page 2 is an image and allow OCR is false, giving up
Exception in thread "main" org.allenai.pdffigures2.FigureExtractor$OcredPdfException: Page 2 is an image and allow OCR is turned off
	at org.allenai.pdffigures2.GraphicsExtractor$.extractRawGraphics(GraphicsExtractor.scala:66)
	at org.allenai.pdffigures2.GraphicsExtractor$.extractGraphics(GraphicsExtractor.scala:32)
	at org.allenai.pdffigures2.FigureExtractor$$anonfun$7.apply(FigureExtractor.scala:133)

**Comment by luomancs** [comment]
> 10:40:30.718 [main] DEBUG o.a.pdffigures2.GraphicsExtractor$ - Page 2 is an image and allow OCR is false, giving up
> Exception in thread "main" org.allenai.pdffigures2.FigureExtractor$OcredPdfException: Page 2 is an image and allow OCR is turned off
> at org.allenai.pdffigures2.GraphicsExtractor$.extractRawGraphics(GraphicsExtractor.scala:66)
> at org.allenai.pdffigures2.GraphicsExtractor$.extractGraphics(GraphicsExtractor.scala:32)
> at org.allenai.pdffigures2.FigureExtractor$$anonfun$7.apply(FigureExtractor.scala:133)
> 
> Did anyone get this error?

have you solve this problem? if so, could you point your solution,  I have the same issue, thank you

**Comment by lucaslioli** [comment]
You can try to enable the OCR option (```allowOcr```) in file ```pdffigures2/src/main/resources/application.conf```

**Comment by rdverse** [comment]
There was no application.conf as indicated by lucaioli in resources folder. However, you can change allowOCR = true here - /src/main/scala/org/allenai/pdffigures2/FigureExtractor.scala
