### ISSUE TITLE
jar file missing pdffigures2

### ISSUE THREAD

**Issue by kapil-mangtani** [allenai/pdffigures2#3]
I am trying to add this as a maven dependency in my project (https://bintray.com/allenai/maven/pdffigures2). In the m2 repository only common-core and testkit jars are downloaded, pdffigures jar is missing, only pom file is present.

**Comment by kapil-mangtani** [comment]
I also tried using the command line tool with no success. Got the following traceback -
java.lang.RuntimeException: Nonzero exit value: 128
	at scala.sys.package$.error(package.scala:27)
	at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:134)
	at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
	at org.allenai.plugins.VersionInjectorPlugin$$anonfun$1.apply$mcJ$sp(VersionInjectorPlugin.scala:76)
	at org.allenai.plugins.VersionInjectorPlugin$$anonfun$1.apply(VersionInjectorPlugin.scala:76)
	at org.allenai.plugins.VersionInjectorPlugin$$anonfun$1.apply(VersionInjectorPlugin.scala:76)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Nonzero exit value: 128
	at scala.sys.package$.error(package.scala:27)
	at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:134)
	at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
	at org.allenai.plugins.VersionInjectorPlugin$$anonfun$5.apply(VersionInjectorPlugin.scala:77)
	at org.allenai.plugins.VersionInjectorPlugin$$anonfun$5.apply(VersionInjectorPlugin.scala:77)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Nonzero exit code: 128
	at scala.sys.package$.error(package.scala:27)
	at sbt.Streamed$.sbt$Streamed$$next$1(ProcessImpl.scala:429)
	at sbt.Streamed$$anonfun$apply$10.apply(ProcessImpl.scala:432)
	at sbt.Streamed$$anonfun$apply$10.apply(ProcessImpl.scala:432)
	at sbt.AbstractProcessBuilder.lines(ProcessImpl.scala:151)
	at sbt.AbstractProcessBuilder.lines(ProcessImpl.scala:141)
	at org.allenai.plugins.VersionInjectorPlugin$$anonfun$6.apply(VersionInjectorPlugin.scala:79)
	at org.allenai.plugins.VersionInjectorPlugin$$anonfun$6.apply(VersionInjectorPlugin.scala:78)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Would be great if you could point out where I'm going wrong!

**Comment by jkinkead** [comment]
Sometimes sbt will cache a broken artifact by mistake. Try removing the cached pdffigures directory and seeing if it recurs:
```bash
rm -r .ivy2/cache/org.allenai*
```

**Comment by kapil-mangtani** [comment]
Tried that but got the same issue.

**Comment by jkinkead** [comment]
This might be a compatibility issue with the pdffigures library and the current version of allenai-common. I think pdffigures might need a new release with updated libraries. I can take a look today.

**Comment by jkinkead** [comment]
Actually, can you send me the exact command you're running which generated that stack trace? Can you also push the branch you're working on to a fork on github so that I can reproduce?

**Comment by dirkgr** [comment]
@jkinkead, I made a new release today. I'd be surprised if it still had any such issues. It went into the AI2 private bintray, so @kapil-mangtani can probably not use it, but you can easily move it.
