### ISSUE TITLE
Error while running with sbt UnsupportedOperationException in The Security Manager

### ISSUE THREAD

**Issue by suraj1074** [allenai/pdffigures2#49]
## Error received

```
38f9d33163ac:pdffigures2$ sbt run
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
copying runtime jar...
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
[info] [launcher] getting org.scala-sbt sbt 1.3.3  (this may take some time)...
[info] [launcher] getting Scala 2.12.10 (for sbt)...
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:416)
	at sbt.TrapExit$.installManager(TrapExit.scala:53)
	at sbt.StandardMain$.runManaged(Main.scala:127)
	at sbt.xMain$.run(Main.scala:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
	at sbt.xMain.run(Main.scala:39)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
```

## Solution
use  -Djava.security.manager=allow for avoid the error.
```
sbt run -Djava.security.manager=allow 
```

**Comment by devacharan** [comment]
using this command - "sbt run -Djava.security.manager=allow"  also reproducing the same error
